image: node:latest

stages:
  - lint
  # - build
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH 

default:
  cache:
    key: 
      prefix: $CI_COMMIT_REF_NAME
      files:
        - server/package-lock.json
        - client/package-lock.json
    paths:
      - server/.npm/
      - client/.npm
  before_script:
   - cd server && npm ci --cache .npm --prefer-offline && cd ../client && npm ci --cache .npm --prefer-offline && cd ..

lint-server:
  stage: lint 
  script:
    - cd server && ./node_modules/eslint/bin/eslint.js --ext js,mjs,cjs . 
  allow_failure: false

lint-client:
  stage: lint 
  script:
    - cd client && ./node_modules/eslint/bin/eslint.js --ext js,jsx,mjs,cjs .
  allow_failure: false


build-frontend:
  stage: build
  cache:
    key:
      prefix: "frontend"
      files:
        - "client/package-lock.json"
    paths:
      - "client/node_modules/"
  script:
    - cd client && npm install && CI=false npm run build
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - client/build
      - client/node_modules

build-backend:
  stage: build
  cache:
    key:
      prefix: "backend"
      files:
        - "server/package-lock.json"
    paths:
      - "server/node_modules/"
  script:
    - cd server && npm install
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - server/node_modules

test-server:
  stage: test
  dependencies:
    - build-backend
  script:
    - npm install jest
    - npm run test
  allow_failure: true